spring:
  application:
    name: keycloak-integration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/master
          jwk-set-uri: http://localhost:8081/realms/master/protocol/openid-connect/certs



